"""Shared fixtures.

``malicious_zip`` is the important one: it builds archives with attributes the
``zipfile`` public API will not produce (symlink members, absolute paths,
traversal names), which is exactly what a real attacker's archive contains.
"""

from __future__ import annotations

import stat
import zipfile
from collections.abc import Callable, Iterator, Sequence
from pathlib import Path

import pytest

from codesmell.config.settings import IngestionSettings, Settings
from codesmell.ingestion.sandbox import Workspace, WorkspaceManager

_MB = 1024 * 1024


@pytest.fixture
def ingestion_settings() -> IngestionSettings:
    """Small limits so bomb tests stay fast and cheap."""
    return IngestionSettings(
        max_archive_bytes=2 * _MB,
        max_uncompressed_bytes=8 * _MB,
        max_member_bytes=1 * _MB,
        max_members=100,
        max_compression_ratio=50.0,
        max_source_file_bytes=512 * 1024,
        max_source_files=500,
    )


@pytest.fixture
def settings(tmp_path: Path, ingestion_settings: IngestionSettings) -> Settings:
    return Settings(
        environment="test",
        workspace_root=tmp_path / "workspaces",
        ingestion=ingestion_settings,
    )


@pytest.fixture
def workspace_manager(settings: Settings) -> WorkspaceManager:
    return WorkspaceManager(settings.workspace_root)


@pytest.fixture
def workspace(workspace_manager: WorkspaceManager) -> Iterator[Workspace]:
    with workspace_manager.session("test-job") as ws:
        yield ws


@pytest.fixture
def make_zip(tmp_path: Path) -> Callable[..., Path]:
    """Build a well-formed ZIP from a ``{name: content}`` mapping."""

    def _build(entries: dict[str, str], name: str = "project.zip") -> Path:
        path = tmp_path / name
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
            for member, content in entries.items():
                archive.writestr(member, content)
        return path

    return _build


@pytest.fixture
def malicious_zip(tmp_path: Path) -> Callable[..., Path]:
    """Build a ZIP containing members the public API refuses to create."""

    def _build(
        members: Sequence[tuple[str, str, int]], name: str = "evil.zip"
    ) -> Path:
        """``members`` is a sequence of ``(filename, content, unix_mode)``."""
        path = tmp_path / name
        with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
            for filename, content, mode in members:
                info = zipfile.ZipInfo(filename)
                info.external_attr = mode << 16
                info.compress_type = zipfile.ZIP_DEFLATED
                archive.writestr(info, content)
        return path

    return _build


@pytest.fixture
def regular_mode() -> int:
    return stat.S_IFREG | 0o644


@pytest.fixture
def symlink_mode() -> int:
    return stat.S_IFLNK | 0o777


@pytest.fixture
def sample_project(tmp_path: Path) -> Path:
    """A small but realistic Python project, complete with noise to filter."""
    root = tmp_path / "sample-project"

    files = {
        "pyproject.toml": (
            "[tool.poetry]\nname = 'sample'\nversion = '0.1.0'\n\n"
            "[tool.poetry.dependencies]\npython = '^3.11'\n"
            "fastapi = '^0.110'\nsqlalchemy = '^2.0'\n"
        ),
        "requirements.txt": "pandas==2.1.0\n# a comment\nnumpy>=1.24\n",
        "src/app/__init__.py": "",
        "src/app/service.py": (
            "class OrderService:\n"
            "    def place(self, order):\n"
            "        return order\n"
        ),
        "src/app/models.py": "class Order:\n    total = 0\n",
        "tests/test_service.py": "def test_place():\n    assert True\n",
        # Everything below must be filtered out.
        "venv/lib/python3.11/site-packages/requests/api.py": "def get(): pass\n",
        "build/generated.py": "x = 1\n",
        "src/app/__pycache__/service.cpython-311.pyc": "\x00\x01binary",
        "node_modules/left-pad/index.js": "module.exports = 1;\n",
        "README.md": "# Sample\n",
        "src/app/schema_pb2.py": "# generated by protoc\n",
    }

    for relative, content in files.items():
        target = root / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")

    (root / "venv" / "pyvenv.cfg").write_text("home = /usr\n", encoding="utf-8")
    return root
